question_in_context:
  description: >
    Você vai precisar analisar a pergunta que foi feita e determinar o assunto
    dela, se o assunto for sobre o mercado condominial brasileiro então você
    poderá seguir com a resposta, se não for, você deve responder que não sabe
    como responder a pergunta.

    Aqui está a pergunta: {question}
  expected_output: >
    Um resposta precisa e bem estrutura, fundamentada, com informações relevantes,
    com um tom bem amigável e que faz sentido para um condomínio brasileiro.
  agent: sub

question_definition:
  description: >
    Você deve analisar a pergunta feita e determinar se é para apenas responder
    algo ou executar algo de alguma forma, se for apenas para responser você
    deve delegar a tarefa para o agente answering_questions_specialist se for
    para executar algo, você deve delegar a tarefa para o agente do determinado
    recurso que foi mencionado na pergunta.

    Aqui está a pergunta: {question}
  expected_output: >
    Retornar o determinado agente que deve ser delegado para a tarefa.
  agent: sub

contextual_response:
  description: >
    Você deve fornecer uma resposta contextual e completa sobre questões condominiais brasileiras.
    Considere o histórico da conversa para manter coerência e continuidade.
    Use o contexto fornecido para entender melhor a situação e dar uma resposta mais precisa.
    
    Contexto da conversa: {conversation_history}
    Pergunta atual: {question}
  expected_output: >
    Uma resposta completa, contextualizada e amigável em português brasileiro,
    considerando o histórico da conversa e fornecendo informações relevantes
    sobre questões condominiais.
  agent: answering_questions_specialist



